name: Periodic Develop Build

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - name: Checkout qmk_firmware
      uses: actions/checkout@v2
      with:
        ref: develop
        repository: 'qmk/qmk_firmware'

    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements-dev.txt
        apt-get update && apt-get install -y rsync nodejs npm doxygen
        npm install -g moxygen

    - name: Build docs
      run: |
        qmk --verbose generate-docs
        rm .build/docs/CNAME
        sed -i "s^basePath: '/'^basePath: '/qmk_docs_devel/'^" .build/docs/index.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: .build/docs
        clean: true
        single-commit: true
        git-config-email: hello@qmk.fm
