name: Periodic Develop Build

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - name: Checkout qmk_firmware
      uses: actions/checkout@v2
      with:
        ref: develop
        repository: 'qmk/qmk_firmware'
        submodules: recursive

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y rsync nodejs npm doxygen
        npm install -g moxygen

    - name: Build docs
      run: |
        qmk --verbose generate-docs

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: main
        BRANCH: gh-pages
        FOLDER: .build/docs
        GIT_CONFIG_EMAIL: hello@qmk.fm
