name: Periodic Develop Build

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - name: Checkout qmk_firmware
      uses: actions/checkout@v2
      with:
        ref: sn32_develop
        repository: 'SonixQMK/qmk_firmware'

    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements-dev.txt
        apt-get update && apt-get install -y rsync nodejs npm doxygen
        touch $HOME/.bashrc
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        source $HOME/.bashrc
        nvm install 20
        nvm use 20
        corepack enable
    
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Build docs
      env:
        CONFIG_FILE: "builddefs/docsgen/.vitepress/config.mts"
      run: |
        source $HOME/.bashrc
        nvm use 20
        sed -i "/description: \"Documentation for QMK Firmware\",/a\        base: '/qmk_docs/'," "$CONFIG_FILE"
        sed -i 's|QMK|SonixQMK|g' "$CONFIG_FILE"
        sed -i "s|github.com/qmk|github.com/SonixQMK|g" "$CONFIG_FILE"
        sed -i 's|discord.gg/[A-Za-z0-9_-]*|discord.gg/gqHaeQYuxS|' "$CONFIG_FILE"
        qmk --verbose generate-docs
        rm .build/docs/CNAME
      
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v1
      with:
          path: ".build/docs"

  deploy-coverage:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
